const teamFlags: Record<string, string> = {
  "África do Sul": "🇿🇦",
  Alemanha: "🇩🇪",
  Argélia: "🇩🇿",
  Argentina: "🇦🇷",
  "Arábia Saudita": "🇸🇦",
  Austrália: "🇦🇺",
  Bélgica: "🇧🇪",
  "Bósnia e Herzegovina": "🇧🇦",
  Brasil: "🇧🇷",
  "Cabo Verde": "🇨🇻",
  Canadá: "🇨🇦",
  Catar: "🇶🇦",
  Colômbia: "🇨🇴",
  "Coreia do Sul": "🇰🇷",
  "Costa do Marfim": "🇨🇮",
  Croácia: "🇭🇷",
  Curaçao: "🇨🇼",
  Egito: "🇪🇬",
  Equador: "🇪🇨",
  Escócia: "🏴",
  Espanha: "🇪🇸",
  "Estados Unidos": "🇺🇸",
  França: "🇫🇷",
  Haiti: "🇭🇹",
  Holanda: "🇳🇱",
  Inglaterra: "🏴",
  Irã: "🇮🇷",
  Iraque: "🇮🇶",
  Japão: "🇯🇵",
  Marrocos: "🇲🇦",
  México: "🇲🇽",
  Noruega: "🇳🇴",
  "Nova Zelândia": "🇳🇿",
  Paraguai: "🇵🇾",
  Portugal: "🇵🇹",
  "República Tcheca": "🇨🇿",
  Senegal: "🇸🇳",
  Suécia: "🇸🇪",
  Suíça: "🇨🇭",
  Tunísia: "🇹🇳",
  Turquia: "🇹🇷",
  Uruguai: "🇺🇾",
};

export function flagForTeam(teamName: string) {
  return teamFlags[teamName] ?? "";
}
